# Generated by Django 5.2.7 on 2025-11-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalmeasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalmeasure',
            name='amplitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Potência do sinal'),
        ),
    ]
