# Generated by Django 5.2.7 on 2025-11-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalmeasure', '0002_alter_signalmeasure_amplitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCableMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency', models.FloatField(verbose_name='Medição latência(Cabeada)')),
                ('transfer_rate', models.FloatField(verbose_name='Taxa de transferência(Cabeada)')),
                ('connection_type', models.CharField(verbose_name='Tipo Conexão')),
                ('timestamp', models.DateField(auto_now=True, verbose_name='Horario do teste')),
            ],
        ),
        migrations.RemoveField(
            model_name='signalmeasure',
            name='user',
        ),
        migrations.AddField(
            model_name='signalmeasure',
            name='connection_type',
            field=models.CharField(blank=True, null=True, verbose_name='Tipo de conexão(Não cabeada)'),
        ),
        migrations.AddField(
            model_name='signalmeasure',
            name='latency',
            field=models.FloatField(default=1, help_text='Medição da latência(Não cabeada)', verbose_name='Latência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signalmeasure',
            name='transfer_rate',
            field=models.FloatField(default=1, help_text='Taxa de transferência(Não cabeada)', verbose_name='Taxa de transferência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signalmeasure',
            name='bssid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='BSSID'),
        ),
        migrations.AlterField(
            model_name='signalmeasure',
            name='frequency',
            field=models.FloatField(blank=True, help_text='Frequência em MHz ou GHZ', null=True, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='signalmeasure',
            name='period',
            field=models.FloatField(blank=True, help_text='Período de medição ou latência em segundos', null=True, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='signalmeasure',
            name='ssid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SSID'),
        ),
        migrations.AlterField(
            model_name='signalmeasure',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Horário do teste(Não cabeado)'),
        ),
    ]
