# Generated by Django 5.2.7 on 2025-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalmeasure', '0003_signalcablemeasure_remove_signalmeasure_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalcablemeasure',
            name='connection_type',
            field=models.CharField(blank=True, null=True, verbose_name='Tipo Conexão'),
        ),
        migrations.AlterField(
            model_name='signalcablemeasure',
            name='transfer_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Taxa de transferência(Cabeada)'),
        ),
    ]
