# Generated by Django 5.2.7 on 2025-11-15 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalmeasure', '0003_signalcablemeasure_remove_signalmeasure_user_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signal_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signalmeasure.signalmeasure'),
        ),
        migrations.AddField(
            model_name='user',
            name='signal_measure_cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='signalmeasure.signalcablemeasure'),
        ),
    ]
